# Generated by Django 4.0.6 on 2022-07-27 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Приоритет')),
                ('status', models.TextField(choices=[('CREATED', 'Created'), ('STARTED', 'Started'), ('STOPED', 'Stoped')], default='created', max_length=20, verbose_name='Статус')),
                ('time_created', models.TimeField(verbose_name='Время создания')),
                ('users', models.ManyToManyField(related_name='objects', to='worker.user', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
    ]
